### ISSUE TITLE
执行  npm start 报这个错  怎么解决？

### ISSUE THREAD

**Issue by zhaolong-benhu** [djwxfdt/fits#1]
执行 run npm install -g bower && npm install  然后 npm start 报这个错 
![Uploading 1490967795(1).jpg…]()

**Comment by zhaolong-benhu** [comment]
E:\Work\fits\src\server\routes.js:25
                for(let [k,v] of Object.entries(mod)){
                                        ^

TypeError: Object.entries is not a function
    at controllers.map.item (E:\Work\fits\src\server\routes.js:25:27)
    at Array.map (native)
    at module.exports.app (E:\Work\fits\src\server\routes.js:22:14)
    at Object.<anonymous> (E:\Work\fits\src\index.js:37:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by djwxfdt** [comment]
Make sure the version of nodejs  greater than 6.5.0.
